{
 "title": "Microclimate",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"microclimate\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"Temperature\")"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"microclimate\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"Temperature\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"microclimate\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"Humidity\")"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"microclimate\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"Humidity\")\r\n  |> last()"
    }
   ]
  }
 ]
}